### ISSUE TITLE
Proxy from environment is ignored when using Custom CA bundles

### ISSUE THREAD

**Issue by Meallia** [zachomedia/cert-manager-webhook-pdns#17]
When trying to use a custom CA bundle and a proxy provided through environment variables, the ACME challenge fails with the following error:
```
failed loading existing records for _acme-challenge.example.com.
in domain example.com.: failed loading zone example.com.:
Get "https://pdns-api:443/api/v1/servers/localhost/zones/example.com":
dial tcp: lookup pdns-api on 10.247.3.10:53: no such host
```
If no CA bundle is provided, the powerdns clients reaches the API through the proxy but fails with an SSL error:
```
failed loading existing records for _acme-challenge.example.com.
in domain example.com.: failed loading zone example.com.:
Get "https://pdns-api:443/api/v1/servers/localhost/zones/example.com":
x509: certificate signed by unknown authority
```

The customized transport with the CA bundle disregards proxy passed by env.

**Comment by zachomedia** [comment]
Thanks for the report!

I did find that a `Clone` method was added to the `Transport` struct (https://github.com/golang/go/issues/26013), so I'll try quickly to see if I can get that to work; otherwise I'll go with the simple fix you provided!

**Comment by zachomedia** [comment]
Release v2.1.1 (Helm chart v2.1.2) should have the fix for this now!

Thanks again for the report :)

**Comment by zachomedia** [comment]
I've also added a test case for this, so it will be tested with future updates.
