### ISSUE TITLE
dns clusserissuer cannot run. it did not find expected key.

### ISSUE THREAD

**Issue by lillianphyoe** [zachomedia/cert-manager-webhook-pdns#2]
Hello, can you please help me? I think I could successfully run cert-manager-webhook-pdns. After that, I can't install cluster issuer. This is my clusterissuer and error. 
![image](https://user-images.githubusercontent.com/19262583/93024589-a58a2500-f61d-11ea-9f08-77eba6d159ed.png)
![image](https://user-images.githubusercontent.com/19262583/93024640-d5d1c380-f61d-11ea-8a94-fd7927525aa4.png)

**Comment by zachomedia** [comment]
@lillianphyoe I sincerely apologize for the very long response time. For some reason my notifications got disabled for this project.

Are you still having issues? I believe in this case the indentation of the `host` in your provider config  line is incorrect, which is causing the YAML to be invalid.

**Comment by lillianphyoe** [comment]
@zachomedia  Not yet brother. I am running with node local dns now. Later I will try for this. Thank you so much for the reply. I cannot test because I tear down the cluster and new setup. Let me close for now and I will reopen if error happen when I test again.
