### ISSUE TITLE
move to unprivileged containerPort

### ISSUE THREAD

**Issue by alexminder** [zachomedia/cert-manager-webhook-pdns#24]
`containerPort: 443` is hardcoded in to charts.

It requires to run pod in privileged mode:
```
securityContext:
        runAsUser: 0
        runAsGroup: 0
```
And for OpenShift configure SCC require:
```
$ oc adm policy add-scc-to-user privileged -z system:serviceaccount:<NS>:<SA>
```

These are pointless actions and security downgrades. Can you change to unprivileged port, 8443?

**Comment by zachomedia** [comment]
Hello @alexminder, thanks for this request. I'll take a look to see what can be done for this as the webserver is setup by the upstream libraries.

**Comment by zachomedia** [comment]
Chart version v2.2.0 should now resolve this issue :)
