### ISSUE TITLE
add labels app.kubernetes.io/name and app.kubernetes.io/instance

### ISSUE THREAD

**Issue by stephbat** [zachomedia/cert-manager-webhook-pdns#27]
Hello
I would like to know if it's possible to add the labels 'app.kubernetes.io/name' and 'app.kubernetes.io/instance' on the deployment.
I have this request in order to be compliant with the kyverno policy require-labels.
Thanks

**Comment by zachomedia** [comment]
@stephbat Apologies for the delay - a new version of the chart is now available with the updated labels!
