### ISSUE TITLE
update version to cert-manager.io/v1

### ISSUE THREAD

**Issue by nevishs** [zachomedia/cert-manager-webhook-pdns#4]
Could you please apply changed to create certificate with apiVersion cert-manager.io/v1.

This is not working for me as I am getting the following error on the cert-manager challenge:
`Reason: the server could not find the requested resource (post pdns.acme.xx.xx)`

Any hit/ideas is appreciated .....

**Comment by unixfox** [comment]
bump

**Comment by iceman91176** [comment]
Hi @zachomedia - any plans to integrate that PR ?
Thanks

**Comment by zachomedia** [comment]
Apologies everyone, not sure what happened to my notifications on this project, but I will take a look at the PR now.

**Comment by zachomedia** [comment]
I have merged in the PR, updated the Helm chart, and confirmed that everything is working with the latest cert-manager.
