### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by mamccorm** [zachomedia/cert-manager-webhook-pdns#50]
Hi there,

Noticed there hasn't been a release tag cut since August 2023, and the last main branch commit was ~8 months ago. Is this project being actively maintained or reaching EOL?

**Comment by mamccorm** [comment]
If still maintained, could we cut a new release to bump the go version? Prepared a PR: https://github.com/zachomedia/cert-manager-webhook-pdns/pull/51

**Comment by zachomedia** [comment]
Hello @mamccorm, this project is still maintained. It is definitely overdue for a release. I will take a look at PR #51 and get it merged and release a new version :) Thanks!

**Comment by mamccorm** [comment]
Awesome, thanks @zachomedia really appreciated
