### ISSUE TITLE
Documentation Request

### ISSUE THREAD

**Issue by vdnclodio** [zachomedia/cert-manager-webhook-pdns#8]
Hi,

By reading the documentation and comparing with the official cert-manager documentation, i'm wondering what are the correct steps to install this cert-manager-plugin.

Should i install cert-manager first, then this plugin ? If not, what about the CRDs ? Does the Helm charts automatically take care of CRD creation ? or should i just create the CRDs manually as per cert-manager doc, and just replace the cert-manager install part with the one from this module ?

Just a bit confuse about how to put it together. Any insights ?

Best regards,

**Comment by zachomedia** [comment]
Hello @vdnclodio,

The correct installation order would be to install cert-manager first, following the instructions at https://cert-manager.io/docs/installation/.

Then, to install this webhook plugin, you can follow the installation instructions in the README: https://github.com/zachomedia/cert-manager-webhook-pdns#installing. This plugin doesn't replace cert-manager, instead it exposes a webhook that cert-manager will call to insert the appropriate DNS records to perform the domain validation.

Following that, you would make your `Issuer` (or `ClusterIssuer`). If you want to learn more about that in https://cert-manager.io/docs/concepts/issuer/. An example configuration that uses this plugin is also provided in the README: https://github.com/zachomedia/cert-manager-webhook-pdns#issuerclusterissuer

After that, all you need to do is make your `Certificate` objects and cert-manager will do the rest!

I hope that helps! Let me know if you have any more questions.
